-- EPAS 전용(Oracle 호환) 샘플 데이터/객체 스크립트
-- PostgreSQL에서는 동작하지 않는 문법/객체를 의도적으로 포함합니다.

CREATE SCHEMA IF NOT EXISTS demo;

CREATE TABLE IF NOT EXISTS demo.customers (
  customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name VARCHAR2(100) NOT NULL,
  email VARCHAR2(200) UNIQUE NOT NULL,
  created_at DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE IF NOT EXISTS demo.orders (
  order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT NOT NULL REFERENCES demo.customers(customer_id),
  product_name VARCHAR2(100) NOT NULL,
  quantity NUMBER(10) NOT NULL,
  unit_price NUMBER(12,2) NOT NULL,
  ordered_at DATE DEFAULT SYSDATE NOT NULL
);

-- Oracle 타입 호환 (CLOB/BLOB)
CREATE TABLE IF NOT EXISTS demo.customer_docs (
  doc_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT NOT NULL REFERENCES demo.customers(customer_id),
  doc_name VARCHAR2(200) NOT NULL,
  doc_text CLOB,
  doc_bin BLOB,
  created_at DATE DEFAULT SYSDATE
);

-- EPAS Oracle profile
DO $$
BEGIN
  EXECUTE 'CREATE PROFILE demo_app_profile LIMIT SESSIONS_PER_USER 5 PASSWORD_LIFE_TIME 30';
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END
$$;

-- Oracle 호환 구문: dual + sysdate
-- (현재 대상 EPAS 환경에서 MERGE 구문 오류가 발생하여 NOT EXISTS 방식으로 구성)
INSERT INTO demo.customers (customer_name, email, created_at)
SELECT s.customer_name, s.email, SYSDATE
  FROM (
    SELECT 'Kim Minjun' AS customer_name, 'minjun@example.com' AS email FROM dual
    UNION ALL SELECT 'Lee Seoyeon', 'seoyeon@example.com' FROM dual
    UNION ALL SELECT 'Park Jiho', 'jiho@example.com' FROM dual
  ) s
 WHERE NOT EXISTS (
   SELECT 1
     FROM demo.customers c
    WHERE c.email = s.email
 );

INSERT INTO demo.orders (customer_id, product_name, quantity, unit_price, ordered_at)
SELECT c.customer_id, s.product_name, s.quantity, s.unit_price, SYSDATE
  FROM (
    SELECT 'minjun@example.com' AS email, 'Laptop' AS product_name, 1 AS quantity, 1499.00 AS unit_price FROM dual
    UNION ALL SELECT 'minjun@example.com', 'Mouse', 2, 25.50 FROM dual
    UNION ALL SELECT 'seoyeon@example.com', 'Monitor', 1, 320.00 FROM dual
    UNION ALL SELECT 'jiho@example.com', 'Keyboard', 1, 85.00 FROM dual
  ) s
  JOIN demo.customers c
    ON c.email = s.email
 WHERE NOT EXISTS (
   SELECT 1
     FROM demo.orders o
    WHERE o.customer_id = c.customer_id
      AND o.product_name = s.product_name
      AND o.quantity = s.quantity
      AND o.unit_price = s.unit_price
 );

-- Synonym (EPAS Oracle 호환)
CREATE OR REPLACE SYNONYM demo.customer_syn FOR demo.customers;

-- Package (EPAS Oracle 호환)
CREATE OR REPLACE PACKAGE demo.pkg_order_api IS
END pkg_order_api;

-- Procedure (EPAS 전용 language: edbspl)
CREATE OR REPLACE PROCEDURE demo.pr_add_order(
  p_email        VARCHAR2,
  p_product_name VARCHAR2,
  p_quantity     NUMBER,
  p_unit_price   NUMBER
)
LANGUAGE edbspl
AS $$
DECLARE
  v_customer_id BIGINT;
BEGIN
  SELECT customer_id
    INTO v_customer_id
    FROM demo.customers
   WHERE email = p_email;

  INSERT INTO demo.orders (customer_id, product_name, quantity, unit_price, ordered_at)
  VALUES (v_customer_id, p_product_name, p_quantity, p_unit_price, SYSDATE);
END;
$$;

-- Function (EPAS 전용 language: edbspl)
CREATE OR REPLACE FUNCTION demo.fn_total_amount(p_email VARCHAR2)
RETURNS NUMBER
LANGUAGE edbspl
AS $$
DECLARE
  v_total NUMBER;
BEGIN
  SELECT NVL(SUM(o.quantity * o.unit_price), 0)
    INTO v_total
    FROM demo.orders o
    JOIN demo.customers c ON c.customer_id = o.customer_id
   WHERE c.email = p_email;

  RETURN v_total;
END;
$$;

-- 약 500MB 샘플 데이터 적재(대용량 CLOB)
-- 재실행 시 누적량이 500MB(1MB x 500건) 수준이 되도록 부족분만 추가합니다.
DO $$
DECLARE
  v_target_mb INTEGER := 500;
  v_existing_rows INTEGER;
  v_missing_rows INTEGER;
BEGIN
  SELECT COUNT(*)
    INTO v_existing_rows
    FROM demo.customer_docs
   WHERE doc_name LIKE 'bulk_doc_%';

  v_missing_rows := GREATEST(v_target_mb - v_existing_rows, 0);

  IF v_missing_rows > 0 THEN
    INSERT INTO demo.customer_docs (customer_id, doc_name, doc_text, doc_bin, created_at)
    SELECT c.customer_id,
           'bulk_doc_' || TO_CHAR(gs),
           CAST(REPEAT('X', 1024 * 1024) AS CLOB),
           NULL,
           SYSDATE
      FROM generate_series(v_existing_rows + 1, v_existing_rows + v_missing_rows) gs
      CROSS JOIN (
        SELECT customer_id
          FROM demo.customers
         WHERE email = 'minjun@example.com'
         FETCH FIRST 1 ROW ONLY
      ) c;
  END IF;
END
$$;

-- 컬럼 암호화 예시(DBMS_CRYPTO 패키지)
INSERT INTO demo.customer_docs (customer_id, doc_name, doc_text, doc_bin, created_at)
SELECT c.customer_id,
       'encrypted_note',
       NULL,
       DBMS_CRYPTO.ENCRYPT(
         UTL_I18N.STRING_TO_RAW('EPAS only encrypted note', 'AL32UTF8'),
         DBMS_CRYPTO.ENCRYPT_AES256 + DBMS_CRYPTO.CHAIN_CBC + DBMS_CRYPTO.PAD_PKCS5,
         UTL_RAW.CAST_TO_RAW('EPAS_DEMO_AES256_KEY_32BYTES__123')
       ),
       SYSDATE
  FROM demo.customers c
 WHERE c.email = 'minjun@example.com'
   AND NOT EXISTS (
     SELECT 1
       FROM demo.customer_docs d
      WHERE d.customer_id = c.customer_id
        AND d.doc_name = 'encrypted_note'
   );

-- Policy(VPD) function + policy 등록
CREATE OR REPLACE FUNCTION demo.fn_customer_policy(
  p_schema_name VARCHAR2,
  p_object_name VARCHAR2
)
RETURNS VARCHAR2
LANGUAGE edbspl
AS $$
BEGIN
  RETURN 'email = SYS_CONTEXT(''USERENV'', ''SESSION_USER'')';
END;
$$;

DO $$
BEGIN
  BEGIN
    PERFORM DBMS_RLS.DROP_POLICY('DEMO', 'CUSTOMERS', 'CUSTOMER_EMAIL_POLICY');
  EXCEPTION
    WHEN OTHERS THEN
      NULL;
  END;

  PERFORM DBMS_RLS.ADD_POLICY(
    object_schema   => 'DEMO',
    object_name     => 'CUSTOMERS',
    policy_name     => 'CUSTOMER_EMAIL_POLICY',
    function_schema => 'DEMO',
    policy_function => 'FN_CUSTOMER_POLICY',
    statement_types => 'SELECT'
  );
END
$$;
