-- EPAS 전용(Oracle 호환) 샘플 데이터/객체 스크립트
-- PostgreSQL에서는 동작하지 않는 문법/객체를 의도적으로 포함합니다.

CREATE SCHEMA IF NOT EXISTS demo;

CREATE TABLE IF NOT EXISTS demo.customers (
  customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name VARCHAR2(100) NOT NULL,
  email VARCHAR2(200) UNIQUE NOT NULL,
  created_at DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE IF NOT EXISTS demo.orders (
  order_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id NUMBER NOT NULL REFERENCES demo.customers(customer_id),
  product_name VARCHAR2(100) NOT NULL,
  quantity NUMBER(10) NOT NULL,
  unit_price NUMBER(12,2) NOT NULL,
  ordered_at DATE DEFAULT SYSDATE NOT NULL
);

-- Oracle 타입 호환 (CLOB/BLOB)
CREATE TABLE IF NOT EXISTS demo.customer_docs (
  doc_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id NUMBER NOT NULL REFERENCES demo.customers(customer_id),
  doc_name VARCHAR2(200) NOT NULL,
  doc_text CLOB,
  doc_bin BLOB,
  created_at DATE DEFAULT SYSDATE
);

-- EPAS Oracle profile
DO $$
BEGIN
  EXECUTE 'CREATE PROFILE demo_app_profile LIMIT SESSIONS_PER_USER 5 PASSWORD_LIFE_TIME 30';
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END
$$;

-- Oracle 호환 구문: dual + sysdate + merge
MERGE INTO demo.customers c
USING (
  SELECT 'Kim Minjun' AS customer_name, 'minjun@example.com' AS email FROM dual
  UNION ALL SELECT 'Lee Seoyeon', 'seoyeon@example.com' FROM dual
  UNION ALL SELECT 'Park Jiho', 'jiho@example.com' FROM dual
) s
ON (c.email = s.email)
WHEN NOT MATCHED THEN
  INSERT (customer_name, email, created_at)
  VALUES (s.customer_name, s.email, SYSDATE);

MERGE INTO demo.orders o
USING (
  SELECT 'minjun@example.com' AS email, 'Laptop' AS product_name, 1 AS quantity, 1499.00 AS unit_price FROM dual
  UNION ALL SELECT 'minjun@example.com', 'Mouse', 2, 25.50 FROM dual
  UNION ALL SELECT 'seoyeon@example.com', 'Monitor', 1, 320.00 FROM dual
  UNION ALL SELECT 'jiho@example.com', 'Keyboard', 1, 85.00 FROM dual
) s
ON (
  o.customer_id = (SELECT customer_id FROM demo.customers WHERE email = s.email)
  AND o.product_name = s.product_name
)
WHEN NOT MATCHED THEN
  INSERT (customer_id, product_name, quantity, unit_price, ordered_at)
  VALUES ((SELECT customer_id FROM demo.customers WHERE email = s.email), s.product_name, s.quantity, s.unit_price, SYSDATE);

-- Synonym (EPAS Oracle 호환)
CREATE OR REPLACE SYNONYM demo.customer_syn FOR demo.customers;

-- Package (EPAS Oracle 호환)
CREATE OR REPLACE PACKAGE demo.pkg_order_api IS
END pkg_order_api;

-- Procedure (EPAS 전용 language: edbspl)
CREATE OR REPLACE PROCEDURE demo.pr_add_order(
  p_email        VARCHAR2,
  p_product_name VARCHAR2,
  p_quantity     NUMBER,
  p_unit_price   NUMBER
)
LANGUAGE edbspl
AS $$
DECLARE
  v_customer_id NUMBER;
BEGIN
  SELECT customer_id
    INTO v_customer_id
    FROM demo.customers
   WHERE email = p_email;

  INSERT INTO demo.orders (customer_id, product_name, quantity, unit_price, ordered_at)
  VALUES (v_customer_id, p_product_name, p_quantity, p_unit_price, SYSDATE);
END;
$$;

-- Function (EPAS 전용 language: edbspl)
CREATE OR REPLACE FUNCTION demo.fn_total_amount(p_email VARCHAR2)
RETURNS NUMBER
LANGUAGE edbspl
AS $$
DECLARE
  v_total NUMBER;
BEGIN
  SELECT NVL(SUM(o.quantity * o.unit_price), 0)
    INTO v_total
    FROM demo.orders o
    JOIN demo.customers c ON c.customer_id = o.customer_id
   WHERE c.email = p_email;

  RETURN v_total;
END;
$$;

-- 컬럼 암호화 예시(DBMS_CRYPTO 패키지)
INSERT INTO demo.customer_docs (customer_id, doc_name, doc_text, doc_bin, created_at)
SELECT c.customer_id,
       'encrypted_note',
       NULL,
       DBMS_CRYPTO.ENCRYPT(
         UTL_I18N.STRING_TO_RAW('EPAS only encrypted note', 'AL32UTF8'),
         DBMS_CRYPTO.ENCRYPT_AES256 + DBMS_CRYPTO.CHAIN_CBC + DBMS_CRYPTO.PAD_PKCS5,
         UTL_RAW.CAST_TO_RAW('EPAS_DEMO_AES256_KEY_32BYTES__123')
       ),
       SYSDATE
  FROM demo.customers c
 WHERE c.email = 'minjun@example.com'
   AND NOT EXISTS (
     SELECT 1
       FROM demo.customer_docs d
      WHERE d.customer_id = c.customer_id
        AND d.doc_name = 'encrypted_note'
   );

-- Policy(VPD) function + policy 등록
CREATE OR REPLACE FUNCTION demo.fn_customer_policy(
  p_schema_name VARCHAR2,
  p_object_name VARCHAR2
)
RETURNS VARCHAR2
LANGUAGE edbspl
AS $$
BEGIN
  RETURN 'email = SYS_CONTEXT(''USERENV'', ''SESSION_USER'')';
END;
$$;

DO $$
BEGIN
  BEGIN
    PERFORM DBMS_RLS.DROP_POLICY('DEMO', 'CUSTOMERS', 'CUSTOMER_EMAIL_POLICY');
  EXCEPTION
    WHEN OTHERS THEN
      NULL;
  END;

  PERFORM DBMS_RLS.ADD_POLICY(
    object_schema   => 'DEMO',
    object_name     => 'CUSTOMERS',
    policy_name     => 'CUSTOMER_EMAIL_POLICY',
    function_schema => 'DEMO',
    policy_function => 'FN_CUSTOMER_POLICY',
    statement_types => 'SELECT'
  );
END
$$;
