-- EPAS 전용(Oracle 호환) 샘플 데이터/객체 스크립트
-- PostgreSQL에서는 동작하지 않는 문법/객체를 의도적으로 포함합니다.

CREATE SCHEMA IF NOT EXISTS demo;

CREATE TABLE IF NOT EXISTS demo.customers (
  customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name VARCHAR2(100) NOT NULL,
  email VARCHAR2(200) UNIQUE NOT NULL,
  created_at DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE IF NOT EXISTS demo.orders (
  order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT NOT NULL REFERENCES demo.customers(customer_id),
  product_name VARCHAR2(100) NOT NULL,
  quantity NUMBER(10) NOT NULL,
  unit_price NUMBER(12,2) NOT NULL,
  ordered_at DATE DEFAULT SYSDATE NOT NULL
);

-- Oracle 타입 호환 (CLOB/BLOB)
CREATE TABLE IF NOT EXISTS demo.customer_docs (
  doc_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT NOT NULL REFERENCES demo.customers(customer_id),
  doc_name VARCHAR2(200) NOT NULL,
  doc_text CLOB,
  doc_bin BLOB,
  created_at DATE DEFAULT SYSDATE
);

-- 다양한 타입 샘플(최소 10개 타입)
CREATE TABLE IF NOT EXISTS demo.type_samples (
  sample_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  v_varchar2 VARCHAR2(100),
  v_char CHAR(10),
  v_number NUMBER(18,4),
  v_integer INTEGER,
  v_date DATE,
  v_timestamp TIMESTAMP,
  v_clob CLOB,
  v_blob BLOB,
  v_nvarchar2 NVARCHAR2(100),
  v_interval INTERVAL DAY TO SECOND,
  v_flag CHAR(1)
);

-- 데이터 분산 저장용 추가 테이블들
CREATE TABLE IF NOT EXISTS demo.large_text_chunks (
  chunk_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chunk_name VARCHAR2(100) UNIQUE,
  chunk_text CLOB,
  created_at DATE DEFAULT SYSDATE
);

CREATE TABLE IF NOT EXISTS demo.large_binary_chunks (
  chunk_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chunk_name VARCHAR2(100) UNIQUE,
  chunk_bin BLOB,
  created_at DATE DEFAULT SYSDATE
);

-- EPAS Oracle profile
DO $$
BEGIN
  EXECUTE 'CREATE PROFILE demo_app_profile LIMIT SESSIONS_PER_USER 5 PASSWORD_LIFE_TIME 30';
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END
$$;

-- Oracle 호환 구문: dual + sysdate
INSERT INTO demo.customers (customer_name, email, created_at)
SELECT s.customer_name, s.email, SYSDATE
  FROM (
    SELECT 'Kim Minjun' AS customer_name, 'minjun@example.com' AS email FROM dual
    UNION ALL SELECT 'Lee Seoyeon', 'seoyeon@example.com' FROM dual
    UNION ALL SELECT 'Park Jiho', 'jiho@example.com' FROM dual
  ) s
 WHERE NOT EXISTS (
   SELECT 1 FROM demo.customers c WHERE c.email = s.email
 );

INSERT INTO demo.orders (customer_id, product_name, quantity, unit_price, ordered_at)
SELECT c.customer_id, s.product_name, s.quantity, s.unit_price, SYSDATE
  FROM (
    SELECT 'minjun@example.com' AS email, 'Laptop' AS product_name, 1 AS quantity, 1499.00 AS unit_price FROM dual
    UNION ALL SELECT 'minjun@example.com', 'Mouse', 2, 25.50 FROM dual
    UNION ALL SELECT 'seoyeon@example.com', 'Monitor', 1, 320.00 FROM dual
    UNION ALL SELECT 'jiho@example.com', 'Keyboard', 1, 85.00 FROM dual
  ) s
  JOIN demo.customers c ON c.email = s.email
 WHERE NOT EXISTS (
   SELECT 1
     FROM demo.orders o
    WHERE o.customer_id = c.customer_id
      AND o.product_name = s.product_name
      AND o.quantity = s.quantity
      AND o.unit_price = s.unit_price
 );

-- Synonym (EPAS Oracle 호환)
CREATE OR REPLACE SYNONYM demo.customer_syn FOR demo.customers;

-- Package (EPAS Oracle 호환)
CREATE OR REPLACE PACKAGE demo.pkg_order_api IS
END pkg_order_api;

-- Procedure (EPAS 전용 language: edbspl)
CREATE OR REPLACE PROCEDURE demo.pr_add_order(
  p_email        VARCHAR2,
  p_product_name VARCHAR2,
  p_quantity     NUMBER,
  p_unit_price   NUMBER
)
LANGUAGE edbspl
AS $$
DECLARE
  v_customer_id BIGINT;
BEGIN
  SELECT customer_id INTO v_customer_id FROM demo.customers WHERE email = p_email;

  INSERT INTO demo.orders (customer_id, product_name, quantity, unit_price, ordered_at)
  VALUES (v_customer_id, p_product_name, p_quantity, p_unit_price, SYSDATE);
END;
$$;

-- Function (EPAS 전용 language: edbspl)
CREATE OR REPLACE FUNCTION demo.fn_total_amount(p_email VARCHAR2)
RETURNS NUMBER
LANGUAGE edbspl
AS $$
DECLARE
  v_total NUMBER;
BEGIN
  SELECT NVL(SUM(o.quantity * o.unit_price), 0)
    INTO v_total
    FROM demo.orders o
    JOIN demo.customers c ON c.customer_id = o.customer_id
   WHERE c.email = p_email;
  RETURN v_total;
END;
$$;

-- 타입 샘플 10건(각 행에 다양한 타입 값 포함)
INSERT INTO demo.type_samples (
  v_varchar2, v_char, v_number, v_integer, v_date, v_timestamp,
  v_clob, v_blob, v_nvarchar2, v_interval, v_flag
)
SELECT
  'sample-' || TO_CHAR(gs),
  RPAD('C' || TO_CHAR(gs), 10, '_'),
  gs * 100.1234,
  gs,
  SYSDATE - gs,
  CURRENT_TIMESTAMP - (gs || ' hour')::INTERVAL,
  CAST('CLOB sample row ' || TO_CHAR(gs) || ' / ' || RPAD('X', 4000, 'X') AS CLOB),
  HEXTORAW(LPAD(TO_CHAR(gs, 'FMXXXXXXXXXXXXXXXX'), 200, 'A')),
  N'unicode-샘플-' || TO_CHAR(gs),
  INTERVAL '1 00:00:00' DAY TO SECOND * gs,
  CASE WHEN MOD(gs, 2) = 0 THEN 'Y' ELSE 'N' END
FROM generate_series(1, 10) gs
WHERE NOT EXISTS (
  SELECT 1 FROM demo.type_samples t WHERE t.v_varchar2 = 'sample-' || TO_CHAR(gs)
);

-- 약 500MB 샘플 데이터를 여러 테이블에 분산 적재
-- 1) customer_docs: 약 170MB (1MB x 170)
DO $$
DECLARE
  v_target_rows INTEGER := 170;
  v_existing_rows INTEGER;
BEGIN
  SELECT COUNT(*) INTO v_existing_rows
  FROM demo.customer_docs
  WHERE doc_name LIKE 'bulk_doc_%';

  IF v_existing_rows < v_target_rows THEN
    INSERT INTO demo.customer_docs (customer_id, doc_name, doc_text, doc_bin, created_at)
    SELECT c.customer_id,
           'bulk_doc_' || TO_CHAR(gs),
           CAST(REPEAT('D', 1024 * 1024) AS CLOB),
           NULL,
           SYSDATE
      FROM generate_series(v_existing_rows + 1, v_target_rows) gs
      CROSS JOIN (
        SELECT customer_id FROM demo.customers WHERE email = 'minjun@example.com' FETCH FIRST 1 ROW ONLY
      ) c;
  END IF;
END
$$;

-- 2) large_text_chunks: 약 170MB (1MB x 170)
DO $$
DECLARE
  v_target_rows INTEGER := 170;
  v_existing_rows INTEGER;
BEGIN
  SELECT COUNT(*) INTO v_existing_rows
  FROM demo.large_text_chunks
  WHERE chunk_name LIKE 'text_chunk_%';

  IF v_existing_rows < v_target_rows THEN
    INSERT INTO demo.large_text_chunks (chunk_name, chunk_text, created_at)
    SELECT 'text_chunk_' || TO_CHAR(gs),
           CAST(REPEAT('T', 1024 * 1024) AS CLOB),
           SYSDATE
      FROM generate_series(v_existing_rows + 1, v_target_rows) gs;
  END IF;
END
$$;

-- 3) large_binary_chunks: 약 170MB (1MB x 170)
DO $$
DECLARE
  v_target_rows INTEGER := 170;
  v_existing_rows INTEGER;
BEGIN
  SELECT COUNT(*) INTO v_existing_rows
  FROM demo.large_binary_chunks
  WHERE chunk_name LIKE 'bin_chunk_%';

  IF v_existing_rows < v_target_rows THEN
    INSERT INTO demo.large_binary_chunks (chunk_name, chunk_bin, created_at)
    SELECT 'bin_chunk_' || TO_CHAR(gs),
           HEXTORAW(RPAD('AB', 2 * 1024 * 1024, 'CD')),
           SYSDATE
      FROM generate_series(v_existing_rows + 1, v_target_rows) gs;
  END IF;
END
$$;

-- 컬럼 암호화 예시(DBMS_CRYPTO 패키지)
-- UTL_I18N 의존성을 제거하고 HEXTORAW를 사용해 환경별 패키지 누락 이슈를 회피
INSERT INTO demo.customer_docs (customer_id, doc_name, doc_text, doc_bin, created_at)
SELECT c.customer_id,
       'encrypted_note',
       NULL,
       DBMS_CRYPTO.ENCRYPT(
         HEXTORAW('45504153206F6E6C7920656E63727970746564206E6F7465'),
         DBMS_CRYPTO.ENCRYPT_AES256 + DBMS_CRYPTO.CHAIN_CBC + DBMS_CRYPTO.PAD_PKCS5,
         HEXTORAW('00112233445566778899AABBCCDDEEFF00112233445566778899AABBCCDDEEFF')
       ),
       SYSDATE
  FROM demo.customers c
 WHERE c.email = 'minjun@example.com'
   AND NOT EXISTS (
     SELECT 1
       FROM demo.customer_docs d
      WHERE d.customer_id = c.customer_id
        AND d.doc_name = 'encrypted_note'
   );

-- Policy(VPD) function + policy 등록
CREATE OR REPLACE FUNCTION demo.fn_customer_policy(
  p_schema_name VARCHAR2,
  p_object_name VARCHAR2
)
RETURNS VARCHAR2
LANGUAGE edbspl
AS $$
BEGIN
  RETURN 'email = SYS_CONTEXT(''USERENV'', ''SESSION_USER'')';
END;
$$;

DO $$
BEGIN
  BEGIN
    PERFORM DBMS_RLS.DROP_POLICY('DEMO', 'CUSTOMERS', 'CUSTOMER_EMAIL_POLICY');
  EXCEPTION
    WHEN OTHERS THEN
      NULL;
  END;

  PERFORM DBMS_RLS.ADD_POLICY(
    object_schema   => 'DEMO',
    object_name     => 'CUSTOMERS',
    policy_name     => 'CUSTOMER_EMAIL_POLICY',
    function_schema => 'DEMO',
    policy_function => 'FN_CUSTOMER_POLICY',
    statement_types => 'SELECT'
  );
END
$$;
