-- EPAS 전용 랜덤 샘플 데이터 생성 스크립트
-- 기존 demo 스키마와 분리된 별도 스키마(demo_cron) 사용

CREATE SCHEMA IF NOT EXISTS demo_cron;

CREATE TABLE IF NOT EXISTS demo_cron.batch_history (
  batch_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_tag VARCHAR2(100) NOT NULL,
  requested_kb NUMBER(10) NOT NULL,
  generated_rows NUMBER(10) NOT NULL,
  created_at DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE IF NOT EXISTS demo_cron.txn_events (
  event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_id BIGINT NOT NULL REFERENCES demo_cron.batch_history(batch_id),
  event_type VARCHAR2(30) NOT NULL,
  amount NUMBER(12,2) NOT NULL,
  status VARCHAR2(20) NOT NULL,
  event_time DATE DEFAULT SYSDATE NOT NULL,
  event_note CLOB
);

CREATE TABLE IF NOT EXISTS demo_cron.sensor_metrics (
  metric_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_id BIGINT NOT NULL REFERENCES demo_cron.batch_history(batch_id),
  device_code VARCHAR2(50) NOT NULL,
  temperature NUMBER(5,2) NOT NULL,
  humidity NUMBER(5,2) NOT NULL,
  metric_time DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE IF NOT EXISTS demo_cron.payload_store (
  payload_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_id BIGINT NOT NULL REFERENCES demo_cron.batch_history(batch_id),
  payload_key VARCHAR2(100) UNIQUE NOT NULL,
  payload_text CLOB,
  payload_bin BLOB,
  created_at DATE DEFAULT SYSDATE NOT NULL
);

ALTER TABLE demo_cron.payload_store ALTER COLUMN payload_text SET STORAGE EXTERNAL;
ALTER TABLE demo_cron.payload_store ALTER COLUMN payload_bin SET STORAGE EXTERNAL;

-- EPAS 함수: 랜덤 텍스트 생성
CREATE OR REPLACE FUNCTION demo_cron.fn_random_clob(p_kb INTEGER)
RETURNS CLOB
LANGUAGE SQL
AS $$
  SELECT CAST(SUBSTRING(STRING_AGG(MD5(RANDOM()::TEXT || gs::TEXT), '') FROM 1 FOR p_kb * 1024) AS CLOB)
  FROM generate_series(1, GREATEST(p_kb * 32, 1)) gs;
$$;

-- EPAS 함수: 최근 배치 생성량 조회
CREATE OR REPLACE FUNCTION demo_cron.fn_last_batch_size()
RETURNS NUMBER
LANGUAGE edbspl
AS $$
DECLARE
  v_rows NUMBER;
BEGIN
  SELECT NVL(generated_rows, 0)
    INTO v_rows
    FROM demo_cron.batch_history
   WHERE batch_id = (SELECT MAX(batch_id) FROM demo_cron.batch_history);

  RETURN NVL(v_rows, 0);
END;
$$;

-- EPAS 프로시저: 호출 시 약 1MB 수준 데이터를 3개 테이블에 랜덤 생성
CREATE OR REPLACE PROCEDURE demo_cron.pr_generate_random_sample(
  p_target_kb NUMBER DEFAULT 1024,
  p_batch_tag VARCHAR2 DEFAULT NULL
)
LANGUAGE edbspl
AS $$
DECLARE
  v_rows NUMBER;
  v_batch_id BIGINT;
  v_tag VARCHAR2(100);
BEGIN
  v_rows := GREATEST(CEIL(p_target_kb / 8), 1); -- row당 약 8KB 기준
  v_tag := NVL(p_batch_tag, 'cron_' || TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'));

  INSERT INTO demo_cron.batch_history(batch_tag, requested_kb, generated_rows, created_at)
  VALUES (v_tag, p_target_kb, v_rows, SYSDATE)
  RETURNING batch_id INTO v_batch_id;

  INSERT INTO demo_cron.txn_events(batch_id, event_type, amount, status, event_time, event_note)
  SELECT v_batch_id,
         CASE MOD(gs, 3)
           WHEN 0 THEN 'PAYMENT'
           WHEN 1 THEN 'REFUND'
           ELSE 'ADJUST'
         END,
         ROUND((RANDOM() * 10000)::NUMERIC, 2),
         CASE MOD(gs, 4)
           WHEN 0 THEN 'OK'
           WHEN 1 THEN 'PENDING'
           WHEN 2 THEN 'FAILED'
           ELSE 'RETRY'
         END,
         SYSDATE,
         demo_cron.fn_random_clob(1)
    FROM generate_series(1, v_rows) gs;

  INSERT INTO demo_cron.sensor_metrics(batch_id, device_code, temperature, humidity, metric_time)
  SELECT v_batch_id,
         'DEV-' || LPAD(gs::TEXT, 6, '0'),
         ROUND((RANDOM() * 50)::NUMERIC, 2),
         ROUND((RANDOM() * 100)::NUMERIC, 2),
         SYSDATE
    FROM generate_series(1, v_rows) gs;

  INSERT INTO demo_cron.payload_store(batch_id, payload_key, payload_text, payload_bin, created_at)
  SELECT v_batch_id,
         v_tag || '_payload_' || gs::TEXT,
         demo_cron.fn_random_clob(6),
         CONVERT_TO(demo_cron.fn_random_clob(2)::TEXT, 'UTF8'),
         SYSDATE
    FROM generate_series(1, v_rows) gs
  ON CONFLICT (payload_key) DO NOTHING;
END;
$$;

-- EPAS 패키지 + 시노님 예시
CREATE OR REPLACE PACKAGE demo_cron.pkg_sample_job AUTHID CURRENT_USER IS
  PROCEDURE run_job(p_target_kb IN NUMBER, p_batch_tag IN VARCHAR2);
  FUNCTION last_rows RETURN NUMBER;
END pkg_sample_job;

CREATE OR REPLACE PACKAGE BODY demo_cron.pkg_sample_job IS
  PROCEDURE run_job(p_target_kb IN NUMBER, p_batch_tag IN VARCHAR2) IS
  BEGIN
    demo_cron.pr_generate_random_sample(p_target_kb, p_batch_tag);
  END run_job;

  FUNCTION last_rows RETURN NUMBER IS
  BEGIN
    RETURN demo_cron.fn_last_batch_size();
  END last_rows;
END pkg_sample_job;

CREATE OR REPLACE SYNONYM demo_cron.sample_job_pkg FOR demo_cron.pkg_sample_job;
CREATE OR REPLACE SYNONYM demo_cron.sample_payload FOR demo_cron.payload_store;
