-- EPAS 전용(Oracle 호환) 샘플 데이터/객체 스크립트
-- PostgreSQL에서는 동작하지 않는 문법/객체를 의도적으로 포함합니다.

CREATE SCHEMA IF NOT EXISTS demo;

CREATE TABLE IF NOT EXISTS demo.customers (
  customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name VARCHAR2(100) NOT NULL,
  email VARCHAR2(200) UNIQUE NOT NULL,
  created_at DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE IF NOT EXISTS demo.orders (
  order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT NOT NULL REFERENCES demo.customers(customer_id),
  product_name VARCHAR2(100) NOT NULL,
  quantity NUMBER(10) NOT NULL,
  unit_price NUMBER(12,2) NOT NULL,
  ordered_at DATE DEFAULT SYSDATE NOT NULL
);


CREATE UNIQUE INDEX IF NOT EXISTS ux_demo_orders_nk
  ON demo.orders (customer_id, product_name, quantity, unit_price);

-- Oracle 타입 호환 (CLOB/BLOB)
CREATE TABLE IF NOT EXISTS demo.customer_docs (
  doc_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT NOT NULL REFERENCES demo.customers(customer_id),
  doc_name VARCHAR2(200) NOT NULL UNIQUE,
  doc_text CLOB,
  doc_bin BLOB,
  created_at DATE DEFAULT SYSDATE
);

-- 다양한 타입 샘플(최소 10개 타입)
CREATE TABLE IF NOT EXISTS demo.type_samples (
  sample_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  v_varchar2 VARCHAR2(100) UNIQUE,
  v_char CHAR(10),
  v_number NUMBER(18,4),
  v_integer INTEGER,
  v_date DATE,
  v_timestamp TIMESTAMP,
  v_clob CLOB,
  v_blob BLOB,
  v_nvarchar2 NVARCHAR2(100),
  v_interval INTERVAL DAY TO SECOND,
  v_flag CHAR(1)
);

-- 데이터 분산 저장용 추가 테이블들
CREATE TABLE IF NOT EXISTS demo.large_text_chunks (
  chunk_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chunk_name VARCHAR2(100) UNIQUE,
  chunk_text CLOB,
  created_at DATE DEFAULT SYSDATE
);

CREATE TABLE IF NOT EXISTS demo.large_binary_chunks (
  chunk_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chunk_name VARCHAR2(100) UNIQUE,
  chunk_bin BLOB,
  created_at DATE DEFAULT SYSDATE
);


-- 대용량 샘플의 실제 디스크 사용량 확인을 위해 TOAST 압축을 피하도록 설정
ALTER TABLE demo.customer_docs ALTER COLUMN doc_text SET STORAGE EXTERNAL;
ALTER TABLE demo.customer_docs ALTER COLUMN doc_bin SET STORAGE EXTERNAL;
ALTER TABLE demo.large_text_chunks ALTER COLUMN chunk_text SET STORAGE EXTERNAL;
ALTER TABLE demo.large_binary_chunks ALTER COLUMN chunk_bin SET STORAGE EXTERNAL;

-- 1MB 페이로드 생성 함수(32자 md5 * 32768 = 1,048,576 bytes)
CREATE OR REPLACE FUNCTION demo.fn_payload_1mb(p_seed TEXT)
RETURNS TEXT
LANGUAGE SQL
IMMUTABLE
AS $$
  SELECT STRING_AGG(MD5(p_seed || ':' || gs::TEXT), '')
  FROM generate_series(1, 32768) gs;
$$;

-- EPAS Oracle profile
DO $$
BEGIN
  EXECUTE 'CREATE PROFILE demo_app_profile LIMIT SESSIONS_PER_USER 5 PASSWORD_LIFE_TIME 30';
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END
$$;

-- Oracle 호환 구문: dual + sysdate
INSERT INTO demo.customers (customer_name, email, created_at)
VALUES
  ('Kim Minjun', 'minjun@example.com', SYSDATE),
  ('Lee Seoyeon', 'seoyeon@example.com', SYSDATE),
  ('Park Jiho', 'jiho@example.com', SYSDATE)
ON CONFLICT (email) DO NOTHING;

INSERT INTO demo.orders (customer_id, product_name, quantity, unit_price, ordered_at)
SELECT c.customer_id, v.product_name, v.quantity, v.unit_price, SYSDATE
  FROM (
    VALUES
      ('minjun@example.com', 'Laptop', 1, 1499.00::NUMERIC),
      ('minjun@example.com', 'Mouse', 2, 25.50::NUMERIC),
      ('seoyeon@example.com', 'Monitor', 1, 320.00::NUMERIC),
      ('jiho@example.com', 'Keyboard', 1, 85.00::NUMERIC)
  ) AS v(email, product_name, quantity, unit_price)
  JOIN demo.customers c ON c.email = v.email
ON CONFLICT (customer_id, product_name, quantity, unit_price) DO NOTHING;

-- Synonym (EPAS Oracle 호환)
CREATE OR REPLACE SYNONYM demo.customer_syn FOR demo.customers;

-- Package (EPAS Oracle 호환)
CREATE OR REPLACE PACKAGE demo.pkg_order_api IS
END pkg_order_api;

-- Procedure (EPAS 전용 language: edbspl)
CREATE OR REPLACE PROCEDURE demo.pr_add_order(
  p_email        VARCHAR2,
  p_product_name VARCHAR2,
  p_quantity     NUMBER,
  p_unit_price   NUMBER
)
LANGUAGE edbspl
AS $$
DECLARE
  v_customer_id BIGINT;
BEGIN
  SELECT customer_id INTO v_customer_id FROM demo.customers WHERE email = p_email;

  INSERT INTO demo.orders (customer_id, product_name, quantity, unit_price, ordered_at)
  VALUES (v_customer_id, p_product_name, p_quantity, p_unit_price, SYSDATE);
END;
$$;

-- Function (EPAS 전용 language: edbspl)
CREATE OR REPLACE FUNCTION demo.fn_total_amount(p_email VARCHAR2)
RETURNS NUMBER
LANGUAGE edbspl
AS $$
DECLARE
  v_total NUMBER;
BEGIN
  SELECT NVL(SUM(o.quantity * o.unit_price), 0)
    INTO v_total
    FROM demo.orders o
    JOIN demo.customers c ON c.customer_id = o.customer_id
   WHERE c.email = p_email;
  RETURN v_total;
END;
$$;

-- 타입 샘플 10건(각 행에 다양한 타입 값 포함)
INSERT INTO demo.type_samples (
  v_varchar2, v_char, v_number, v_integer, v_date, v_timestamp,
  v_clob, v_blob, v_nvarchar2, v_interval, v_flag
)
SELECT
  'sample-' || TO_CHAR(gs),
  RPAD('C' || TO_CHAR(gs), 10, '_'),
  gs * 100.1234,
  gs,
  SYSDATE - gs,
  CURRENT_TIMESTAMP - (gs || ' hour')::INTERVAL,
  CAST('CLOB sample row ' || TO_CHAR(gs) || ' / ' || RPAD('X', 4000, 'X') AS CLOB),
  CONVERT_TO(RPAD(MD5(TO_CHAR(gs)), 200, 'A'), 'UTF8'),
  N'unicode-샘플-' || TO_CHAR(gs),
  INTERVAL '1 00:00:00' DAY TO SECOND * gs,
  CASE WHEN MOD(gs, 2) = 0 THEN 'Y' ELSE 'N' END
FROM generate_series(1, 10) gs
WHERE NOT EXISTS (
  SELECT 1 FROM demo.type_samples t WHERE t.v_varchar2 = 'sample-' || TO_CHAR(gs)
);

-- 약 500MB 샘플 데이터를 여러 테이블에 분산 적재
-- 1) customer_docs: 약 170MB (1MB x 170)
DO $$
DECLARE
  v_target_rows INTEGER := 170;
  v_existing_rows INTEGER;
BEGIN
  SELECT COUNT(*) INTO v_existing_rows
  FROM demo.customer_docs
  WHERE doc_name LIKE 'bulk_doc_%';

  IF v_existing_rows < v_target_rows THEN
    INSERT INTO demo.customer_docs (customer_id, doc_name, doc_text, doc_bin, created_at)
    SELECT c.customer_id,
           'bulk_doc_' || TO_CHAR(gs),
           CAST(demo.fn_payload_1mb('DOC:' || TO_CHAR(gs)) AS CLOB),
           NULL,
           SYSDATE
      FROM generate_series(v_existing_rows + 1, v_target_rows) gs
      CROSS JOIN (
        SELECT customer_id FROM demo.customers WHERE email = 'minjun@example.com' FETCH FIRST 1 ROW ONLY
      ) c;
  END IF;
END
$$;

-- 기존에 압축률이 높은 패턴으로 적재된 경우 디스크 사용량이 작게 보일 수 있어 재작성
DO $$
BEGIN
  IF pg_total_relation_size('demo.customer_docs') < (120 * 1024 * 1024) THEN
    UPDATE demo.customer_docs
       SET doc_text = CAST(demo.fn_payload_1mb('DOC:' || REGEXP_REPLACE(doc_name, '^bulk_doc_', '')) AS CLOB)
     WHERE doc_name LIKE 'bulk_doc_%';
  END IF;
END
$$;

-- 2) large_text_chunks: 약 170MB (1MB x 170)
DO $$
DECLARE
  v_target_rows INTEGER := 170;
  v_existing_rows INTEGER;
BEGIN
  SELECT COUNT(*) INTO v_existing_rows
  FROM demo.large_text_chunks
  WHERE chunk_name LIKE 'text_chunk_%';

  IF v_existing_rows < v_target_rows THEN
    INSERT INTO demo.large_text_chunks (chunk_name, chunk_text, created_at)
    SELECT 'text_chunk_' || TO_CHAR(gs),
           CAST(demo.fn_payload_1mb('TXT:' || TO_CHAR(gs)) AS CLOB),
           SYSDATE
      FROM generate_series(v_existing_rows + 1, v_target_rows) gs;
  END IF;
END
$$;

DO $$
BEGIN
  IF pg_total_relation_size('demo.large_text_chunks') < (120 * 1024 * 1024) THEN
    UPDATE demo.large_text_chunks
       SET chunk_text = CAST(demo.fn_payload_1mb('TXT:' || REGEXP_REPLACE(chunk_name, '^text_chunk_', '')) AS CLOB)
     WHERE chunk_name LIKE 'text_chunk_%';
  END IF;
END
$$;

-- 3) large_binary_chunks: 약 170MB (1MB x 170)
DO $$
DECLARE
  v_target_rows INTEGER := 170;
  v_existing_rows INTEGER;
BEGIN
  SELECT COUNT(*) INTO v_existing_rows
  FROM demo.large_binary_chunks
  WHERE chunk_name LIKE 'bin_chunk_%';

  IF v_existing_rows < v_target_rows THEN
    INSERT INTO demo.large_binary_chunks (chunk_name, chunk_bin, created_at)
    SELECT 'bin_chunk_' || TO_CHAR(gs),
           CONVERT_TO(demo.fn_payload_1mb('BIN:' || TO_CHAR(gs)), 'UTF8'),
           SYSDATE
      FROM generate_series(v_existing_rows + 1, v_target_rows) gs;
  END IF;
END
$$;

DO $$
BEGIN
  IF pg_total_relation_size('demo.large_binary_chunks') < (120 * 1024 * 1024) THEN
    UPDATE demo.large_binary_chunks
       SET chunk_bin = CONVERT_TO(demo.fn_payload_1mb('BIN:' || REGEXP_REPLACE(chunk_name, '^bin_chunk_', '')), 'UTF8')
     WHERE chunk_name LIKE 'bin_chunk_%';
  END IF;
END
$$;

-- 컬럼 암호화 예시(DBMS_CRYPTO 패키지)
-- UTL_I18N 의존성을 제거하고 HEXTORAW를 사용해 환경별 패키지 누락 이슈를 회피
INSERT INTO demo.customer_docs (customer_id, doc_name, doc_text, doc_bin, created_at)
SELECT c.customer_id,
       'encrypted_note',
       NULL,
       DBMS_CRYPTO.ENCRYPT(
         HEXTORAW('45504153206F6E6C7920656E63727970746564206E6F7465'),
         DBMS_CRYPTO.ENCRYPT_AES256 + DBMS_CRYPTO.CHAIN_CBC + DBMS_CRYPTO.PAD_PKCS5,
         HEXTORAW('00112233445566778899AABBCCDDEEFF00112233445566778899AABBCCDDEEFF')
       ),
       SYSDATE
  FROM demo.customers c
 WHERE c.email = 'minjun@example.com'
   AND NOT EXISTS (
     SELECT 1
       FROM demo.customer_docs d
      WHERE d.customer_id = c.customer_id
        AND d.doc_name = 'encrypted_note'
   );



-- SYNONYM 추가 예시(카운트 보강)
CREATE OR REPLACE SYNONYM demo.order_syn FOR demo.orders;

-- PACKAGE + AUTHID 추가 예시(카운트 보강)
CREATE OR REPLACE PACKAGE demo.pkg_text_api AUTHID CURRENT_USER IS
  FUNCTION fn_make_clob(p_seed IN VARCHAR2) RETURN CLOB;
END pkg_text_api;

CREATE OR REPLACE PACKAGE BODY demo.pkg_text_api IS
  FUNCTION fn_make_clob(p_seed IN VARCHAR2) RETURN CLOB IS
    v_txt CLOB;
  BEGIN
    v_txt := TO_CLOB(p_seed || ':' || SYS_CONTEXT('USERENV', 'SESSION_USER'));
    RETURN NVL(v_txt, TO_CLOB('N/A'));
  END fn_make_clob;
END pkg_text_api;



-- === 검출 보강용 EPAS 특화 객체 샘플 ===
-- 1) 비기본 PROFILE (detector: Profile non-default)
DO $$
BEGIN
  BEGIN
    EXECUTE 'CREATE PROFILE demo_non_default_profile LIMIT SESSIONS_PER_USER 3 PASSWORD_LIFE_TIME 45';
  EXCEPTION
    WHEN OTHERS THEN
      NULL;
  END;
END
$$;

-- 2) 패키지/프로시저/함수 내 DBMS/UTL 사용 흔적 (detector: EDB 특화 기능)
CREATE OR REPLACE PROCEDURE demo.pr_pkg_trace
LANGUAGE edbspl
AS $$
DECLARE
  v_raw RAW(2000);
  v_txt VARCHAR2(2000);
BEGIN
  v_raw := UTL_RAW.CAST_TO_RAW('EPAS_TRACE_SAMPLE');
  v_txt := UTL_RAW.CAST_TO_VARCHAR2(v_raw);
  DBMS_OUTPUT.PUT_LINE(v_txt);
END;
$$;

CREATE OR REPLACE FUNCTION demo.fn_pkg_trace(p_text VARCHAR2)
RETURNS VARCHAR2
LANGUAGE edbspl
AS $$
DECLARE
  v_enc RAW(2000);
BEGIN
  v_enc := UTL_ENCODE.BASE64_ENCODE(UTL_RAW.CAST_TO_RAW(p_text));
  RETURN UTL_RAW.CAST_TO_VARCHAR2(v_enc);
END;
$$;

-- 3) RESOURCE GROUP 샘플 (권한/버전에 따라 실패 가능)
DO $$
BEGIN
  BEGIN
    EXECUTE 'CREATE RESOURCE GROUP demo_rg TYPE cpu_rate_limit WITH (cpu_rate_limit=10)';
  EXCEPTION
    WHEN OTHERS THEN
      NULL;
  END;
END
$$;

-- 4) DBLINK 샘플 (권한/환경에 따라 실패 가능)
DO $$
BEGIN
  BEGIN
    EXECUTE 'CREATE DATABASE LINK demo_loopback CONNECT TO CURRENT_USER USING ''localhost''';
  EXCEPTION
    WHEN OTHERS THEN
      NULL;
  END;
END
$$;

-- Policy(VPD) function + policy 등록
CREATE OR REPLACE FUNCTION demo.fn_customer_policy(
  p_schema_name VARCHAR2,
  p_object_name VARCHAR2
)
RETURNS VARCHAR2
LANGUAGE edbspl
AS $$
BEGIN
  RETURN 'email = SYS_CONTEXT(''USERENV'', ''SESSION_USER'')';
END;
$$;

DO $$
BEGIN
  BEGIN
    PERFORM DBMS_RLS.DROP_POLICY('DEMO', 'CUSTOMERS', 'CUSTOMER_EMAIL_POLICY');
  EXCEPTION
    WHEN OTHERS THEN
      NULL;
  END;

  PERFORM DBMS_RLS.ADD_POLICY(
    object_schema   => 'DEMO',
    object_name     => 'CUSTOMERS',
    policy_name     => 'CUSTOMER_EMAIL_POLICY',
    function_schema => 'DEMO',
    policy_function => 'FN_CUSTOMER_POLICY',
    statement_types => 'SELECT'
  );
END
$$;
